### ISSUE TITLE
SV1 Qn5 Missile Capability

### ISSUE THREAD

**Issue by huiyaozheng** [Hava842/AI_I#1]
What is the exact capability of the missile? Can it

- only land on one target OR

- operate in a MIRV style, i.e. release a payload on one city and then continue flying towards another until end of life?

**Comment by mhavasi** [comment]
Hi,

Cool idea! The question refers to a single target missile, but feel free to extend it to multiple targets. As always, make sure to state any assumptions you make.

Best,
Marton
